#!/usr/bin/env python3
"""lean_ledger: annotate a Lean formalization with stable paper tags.

Scans .lean files for paper citations ("Lemma 6.1", "eq. (59)", "Prop 8.9"),
resolves them against snapshot numbering maps (see tex2ptx.py --numbering),
and appends ONE auto-generated, marker-delimited ledger block per file:

    /-! ### Paper-tag ledger (auto-generated by paperforge; do not edit)
    ...one line per distinct citation found in this file...
    -/

Design constraints:
  - additive & idempotent: never rewrites prose; re-running replaces the block.
  - comment-only: cannot break the Lean build.
  - numbering-drift-proof: prose numbers stay as historical readings; the
    ledger says which tag each number denotes in which snapshot.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

MARKER = "Paper-tag ledger (auto-generated by paperforge; do not edit)"
KIND = {"theorem": "theorem", "thm": "theorem", "lemma": "lemma", "lem": "lemma",
        "proposition": "proposition", "prop": "proposition",
        "corollary": "corollary", "cor": "corollary", "remark": "remark",
        "definition": "definition", "claim": "claim"}
STMT_RE = re.compile(
    r"\b(Theorem|Thm|Lemma|Lem|Proposition|Prop|Corollary|Cor|Remark|Definition|Claim)"
    r"\.?~? ?(\d+\.\d+|[AB]\.\d+)", re.I)
EQ_RE = re.compile(r"\beqs?\.? ?\((\d{1,3})\)(?:[–-]+\((\d{1,3})\))?")


def load_maps(current_json: Path, old_json: Path | None):
    cur = json.load(open(current_json))["items"]
    # (kind, number) -> tag and eq number -> tag, for current numbering
    stmt_cur, eq_cur = {}, {}
    for tag, r in cur.items():
        if r["kind"] in KIND.values():
            stmt_cur[(r["kind"], r["number"])] = tag
        elif r["kind"] in ("equation", "align-row"):
            eq_cur[r["number"].strip("()")] = tag
    stmt_old, kind_of_old = {}, {}
    if old_json and old_json.exists():
        old = json.load(open(old_json))  # label -> {old, old_kind}
        for label, rec in old.items():
            tag = re.sub(r"[:_]", "-", label)
            stmt_old[(rec["old_kind"], rec["old"])] = tag
            stmt_old[("any", rec["old"])] = tag
    for (k, n), t in list(stmt_cur.items()):
        stmt_cur.setdefault(("any", n), t)
    return stmt_cur, stmt_old, eq_cur, cur


def resolve_stmt(kind: str, num: str, stmt_old, stmt_cur):
    """Prefer the v428 (old) reading — that is what existing prose cites."""
    for m, via in ((stmt_old, "v428"), (stmt_cur, "current")):
        if (kind, num) in m:
            return m[(kind, num)], via, True
        if ("any", num) in m:
            return m[("any", num)], via, False   # kind-loose match
    return None, None, False


def ledger_for(text: str, stmt_old, stmt_cur, eq_cur, cur_items, eq_window: int):
    lines = {}
    for m in STMT_RE.finditer(text):
        kind, num = KIND[m.group(1).lower()], m.group(2)
        tag, via, kind_ok = resolve_stmt(kind, num, stmt_old, stmt_cur)
        if not tag:
            continue
        cur_rec = cur_items.get(tag, {})
        cur_num = cur_rec.get("number", "?")
        cur_kind = cur_rec.get("kind", kind)
        key = f"{kind} {num}"
        note = f"{cur_kind} {cur_num} in current tex" if (via == "v428" and cur_num != num) else ""
        flag = "" if kind_ok else f" [cited as {kind}; paper says {cur_kind}]"
        entry = f"{m.group(1)} {num} = ⟦{tag}⟧"
        if note:
            entry += f" (= {note})"
        entry += flag
        lines[key] = entry
    for m in EQ_RE.finditer(text):
        for n in filter(None, (m.group(1), m.group(2))):
            tag = eq_cur.get(n)
            if not tag:
                continue
            entry = f"eq. ({n}) = ⟦{tag}⟧"
            if int(n) >= eq_window:
                entry += " [≥ drift window; verify against v428 tex]"
            lines[f"eq {n}"] = entry
    return [lines[k] for k in sorted(lines)]


def apply(path: Path, entries: list[str], dry: bool) -> bool:
    text = path.read_text()
    block = ("\n/-! ### " + MARKER + "\n\n"
             + "\n".join("  * " + e for e in entries)
             + "\n-/\n")
    if MARKER in text:
        new = re.sub(r"\n/-! ### " + re.escape(MARKER) + r".*?-/\n",
                     block, text, flags=re.S)
    else:
        new = text.rstrip("\n") + "\n" + block
    if new != text and not dry:
        path.write_text(new)
    return new != text


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("lean_root", type=Path, help="e.g. ~/claude/gq2-lean/GQ2")
    ap.add_argument("--current", type=Path, required=True)
    ap.add_argument("--old", type=Path, help="matched old-numbering JSON (label -> {old, old_kind})")
    ap.add_argument("--eq-window", type=int, default=10**9,
                    help="equation numbers >= this are drift-flagged")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--audit-out", type=Path, help="write full per-file audit JSON")
    args = ap.parse_args()

    stmt_cur, stmt_old, eq_cur, cur_items = load_maps(args.current, args.old)
    audit, changed = {}, 0
    for f in sorted(args.lean_root.rglob("*.lean")):
        if ".lake" in f.parts:
            continue
        entries = ledger_for(f.read_text(), stmt_old, stmt_cur, eq_cur,
                             cur_items, args.eq_window)
        if not entries:
            continue
        audit[str(f)] = entries
        if apply(f, entries, args.dry_run):
            changed += 1
            print(f"{'would update' if args.dry_run else 'updated'}: {f} ({len(entries)} entries)")
    if args.audit_out:
        args.audit_out.write_text(json.dumps(audit, indent=1, ensure_ascii=False))
    print(f"{changed} file(s) {'would be ' if args.dry_run else ''}updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
