#!/usr/bin/env python3
"""notation_registry: generate the hover registry consumed by detail-ui.js.

Reads the instance's notation map (authored; see notation-map.json) and the
current numbering database (for defsite -> output page resolution) and writes
``web-assets/notation-registry.js``:

    window.paperforgeNotation = { farDelayMs: ..., nearDelayMs: ... };
    window.PAPERFORGE_NOTATION = { key: {html: "...", href: "page.html#id"}, ... };

The registry file must load BEFORE detail-ui.js — the instance build script
concatenates ``notation-registry.js + detail-ui.js`` into the web output.

href resolution: a defsite (or explicit ``href`` field) xml:id lives in some
top-level division; PreTeXt names that division's HTML page after its xml:id,
so the link is ``<division-tag>.html#<defsite>`` (or just ``<tag>.html`` when
the defsite IS the division).
"""
from __future__ import annotations

import argparse
import json
import tomllib
from pathlib import Path


def resolve_href(target: str, items: dict, web: Path | None = None) -> str | None:
    rec = items.get(target)
    if rec is None:
        return None

    def page_or_index(page, frag=""):
        if web is not None and not (web / page).exists():
            singles = [f.name for f in web.glob("*.html")
                       if f.name != "index.html"]
            if len(singles) == 1:          # chunk-0 build: one document page
                page = singles[0]
            elif (web / "index.html").exists():
                page = "index.html"
        return page + frag

    if rec["kind"] in ("section", "appendix"):
        return page_or_index(f"{target}.html")
    # find the division (section/appendix) whose number matches this item's
    sec_no = rec.get("section")
    for tag, r in items.items():
        if r["kind"] in ("section", "appendix") and r["number"] == sec_no:
            return page_or_index(f"{tag}.html", f"#{target}")
    return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("instance", type=Path, nargs="?", default=Path.cwd())
    args = ap.parse_args()
    root = args.instance

    with open(root / "paper.toml", "rb") as fh:
        cfg = tomllib.load(fh)
    ncfg = cfg.get("notation", {})
    map_path = root / ncfg.get("map", "notation/notation-map.json")
    entries = json.load(open(map_path))
    items = json.load(open(root / "crosswalk" / "numbering-current.json"))["items"]

    registry = {}

    def flat(entries):
        for key, rec in entries.items():
            if rec.get("kind") == "ambiguous":
                yield from rec["senses"].items()   # each sense is a key
            else:
                yield key, rec

    for key, rec in flat(entries):
        target = rec.get("href") or rec.get("defsite")
        href = (resolve_href(target, items, root / "output" / "web")
                if target else None)
        registry[key] = {"html": rec["definition"], "href": href}

    out = root / "web-assets" / "notation-registry.js"
    out.write_text(
        "/* auto-generated by paperforge notation_registry.py — do not edit */\n"
        "window.paperforgeNotation = "
        + json.dumps({"farDelayMs": ncfg.get("far_hover_delay_ms", 1000),
                      "nearDelayMs": ncfg.get("near_hover_delay_ms", 150),
                      "defsiteHlDelayMs":
                          ncfg.get("defsite_highlight_delay_ms", 120)})
        + ";\n"
        "window.PAPERFORGE_NOTATION = "
        + json.dumps(registry, indent=1) + ";\n")
    n_href = sum(1 for r in registry.values() if r["href"])
    print(f"wrote {out}: {len(registry)} keys, {n_href} with context links")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
