#!/usr/bin/env python3
"""notation_registry: generate the hover registry consumed by detail-ui.js.

Reads the instance's notation map (authored; see notation-map.json) and the
current numbering database (for defsite -> output page resolution) and writes
``web-assets/notation-registry.js``:

    window.paperforgeNotation = { farDelayMs: ..., nearDelayMs: ... };
    window.PAPERFORGE_NOTATION = { key: {html: "...", href: "page.html#id"}, ... };

The registry file must load BEFORE detail-ui.js — the instance build script
concatenates ``notation-registry.js + detail-ui.js`` into the web output.

href resolution: a defsite (or explicit ``href`` field) xml:id lives in some
top-level division; PreTeXt names that division's HTML page after its xml:id,
so the link is ``<division-tag>.html#<defsite>`` (or just ``<tag>.html`` when
the defsite IS the division).
"""
from __future__ import annotations

import argparse
import json
import tomllib
from pathlib import Path


def resolve_href(target: str, items: dict) -> str | None:
    rec = items.get(target)
    if rec is None:
        return None
    if rec["kind"] in ("section", "appendix"):
        return f"{target}.html"
    # find the division (section/appendix) whose number matches this item's
    sec_no = rec.get("section")
    for tag, r in items.items():
        if r["kind"] in ("section", "appendix") and r["number"] == sec_no:
            return f"{tag}.html#{target}"
    return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("instance", type=Path, nargs="?", default=Path.cwd())
    args = ap.parse_args()
    root = args.instance

    with open(root / "paper.toml", "rb") as fh:
        cfg = tomllib.load(fh)
    ncfg = cfg.get("notation", {})
    map_path = root / ncfg.get("map", "notation/notation-map.json")
    entries = json.load(open(map_path))
    items = json.load(open(root / "crosswalk" / "numbering-current.json"))["items"]

    registry = {}
    for key, rec in entries.items():
        target = rec.get("href") or rec.get("defsite")
        href = resolve_href(target, items) if target else None
        registry[key] = {"html": rec["definition"], "href": href}

    out = root / "web-assets" / "notation-registry.js"
    out.write_text(
        "/* auto-generated by paperforge notation_registry.py — do not edit */\n"
        "window.paperforgeNotation = "
        + json.dumps({"farDelayMs": ncfg.get("far_hover_delay_ms", 1000),
                      "nearDelayMs": ncfg.get("near_hover_delay_ms", 150)})
        + ";\n"
        "window.PAPERFORGE_NOTATION = "
        + json.dumps(registry, indent=1) + ";\n")
    n_href = sum(1 for r in registry.values() if r["href"])
    print(f"wrote {out}: {len(registry)} keys, {n_href} with context links")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
