#!/usr/bin/env python3
"""Give every assembled page the site favicon.

The hand-authored pages under the site source dir carry the icon links in
their own <head>; the rest of the site is generated by tools that know
nothing about them — PreTeXt for /paper/, Verso for /blueprint*/, doc-gen
for /lean/ — so the links are stamped in here, at assembly time, once the
trees are in place.  GitHub Pages serves project sites from a subpath,
where a browser's implicit /favicon.ico lookup misses entirely, so each
page needs an explicit link with a depth-correct relative href.

Idempotent: a page that already links an icon is left alone. Run from
build-site.sh, or by hand on an assembled tree:

    python3 sitegen/apply_favicon.py [site-tree]     (default: output/site)
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

LINKS = """<link rel="icon" href="{prefix}favicon.svg" type="image/svg+xml">
<link rel="alternate icon" href="{prefix}favicon.ico" sizes="16x16 32x32 48x48">
<link rel="apple-touch-icon" href="{prefix}apple-touch-icon.png">
"""


def main() -> None:
    site = Path(sys.argv[1] if len(sys.argv) > 1 else "output/site")
    if not (site / "favicon.svg").exists():
        sys.exit(f"apply-favicon: no favicon.svg at the root of {site}")

    stamped = skipped = 0
    for page in sorted(site.rglob("*.html")):
        html = page.read_text(encoding="utf-8", errors="surrogateescape")
        if "</head>" not in html:  # knowl fragments and other partials
            continue
        if 'rel="icon"' in html:  # hand-authored pages, and reruns
            skipped += 1
            continue
        prefix = "../" * (len(page.relative_to(site).parts) - 1)
        head, sep, tail = html.partition("</head>")
        page.write_text(
            head + LINKS.format(prefix=prefix) + sep + tail,
            encoding="utf-8",
            errors="surrogateescape",
        )
        stamped += 1

    # doc-gen ships its own favicon.svg next to each library's pages, linked
    # from every page it generates; overwriting it is enough to bring the Lean
    # docs into line without touching the generated HTML.
    replaced = 0
    for lean_icon in sorted(site.glob("lean/*/favicon.svg")):
        shutil.copyfile(site / "favicon.svg", lean_icon)
        replaced += 1

    print(
        f"favicon: {stamped} pages stamped, {skipped} already linked, "
        f"{replaced} lean subtree icons replaced"
    )


if __name__ == "__main__":
    main()
