#!/usr/bin/env python3
"""Render the site's status.json into stamped version footers, with a drift gate.

Single-source-of-truth machinery for synchronized version identifiers (the
G_Q2 July 2026 review's §3.2): status.json holds the identifiers, the site
pages carry `<!-- versions:begin -->…<!-- versions:end -->` marker blocks,
and this tool keeps the two in lockstep:

* refreshes the *_auto fields of status.json from the live artifacts
  (formalization checkout HEADs, lean-toolchain, mathlib pin from the lake
  manifest, PDF checksum + page count);
* verifies hand-edited fields against the artifacts they duplicate, as
  declared in paper.toml [site.status.checks.<field>] — `axiom_census`
  counts status=="axiom" entries of a census JSON, `line_count` counts the
  non-blank lines of a file (missing artifacts are skipped) — and FAILS on
  mismatch;
* rewrites every marker block found under <site>/**/index.html (link
  prefixes adjusted per page depth).  The block renders as one line,
  "Manuscript <date> · …", where the date is a knowl expanding to the full
  identifiers: one entry per formalization (with its mathlib note when the
  entry carries one), the [site.status].extras lines formatted over the
  status.json fields, the PDF checksum, and the [site.status] tail link.

Modes:
    gen_status.py [root]            refresh + stamp (used by build-site.sh)
    gen_status.py [root] --check    verify only; exit 1 if anything would
                                    change (documentation-drift gate)
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

from _common import load_config, site_dir, formalization_root

STAMP_NOTE = "(regenerated by paperforge sitegen/gen_status.py from status.json)"


def refresh_auto(root: Path, config: dict, data: dict) -> dict:
    """Fill *_auto fields from the live artifacts."""
    for sub, entry in data["formalizations"].items():
        subdir = formalization_root(root, config, sub)
        entry["commit_auto"] = subprocess.check_output(
            ["git", "-C", str(subdir), "rev-parse", "--short=7", "HEAD"],
            text=True).strip()
        tc = subdir / "lean-toolchain"
        if tc.exists():
            entry["toolchain_auto"] = tc.read_text().strip()
        manifest = subdir / "lake-manifest.json"
        if manifest.exists():
            for pkg in json.loads(manifest.read_text()).get("packages", []):
                if pkg.get("name") == "mathlib":
                    entry["mathlib_commit_auto"] = pkg.get("rev", "")[:7]
    pdf_name = config.get("site", {}).get("pdf")
    pdf = root / pdf_name if pdf_name else None
    if pdf and pdf.exists():
        data["pdf_sha256_auto"] = hashlib.sha256(pdf.read_bytes()).hexdigest()
        try:                        # best effort: pymupdf is in the build env
            import fitz
            data["pdf_pages_auto"] = fitz.open(pdf).page_count
        except Exception:
            pass                    # keep the recorded value rather than lying
    return data


def verify_hand_fields(root: Path, config: dict, data: dict) -> list[str]:
    """Check hand-edited fields against their declared ground truth."""
    errors = []
    checks = config.get("site", {}).get("status", {}).get("checks", {})
    for field, spec in checks.items():
        if "axiom_census" in spec:
            census = root / spec["axiom_census"]
            if not census.exists():
                continue
            entries = json.loads(census.read_text())
            live = sum(1 for v in entries.values() if v.get("status") == "axiom")
            if live != data[field]:
                errors.append(
                    f"status.json {field}={data[field]} but the live census "
                    f"{spec['axiom_census']} has {live} axioms")
        elif "line_count" in spec:
            artifact = Path(spec["line_count"]).expanduser()
            if not artifact.is_absolute():
                artifact = root / artifact
            if not artifact.exists():
                continue
            n = sum(1 for line in artifact.open() if line.strip())
            if n != data[field]:
                errors.append(
                    f"status.json {field}={data[field]} but the local "
                    f"artifact {artifact} has {n} lines")
        else:
            errors.append(f"[site.status.checks.{field}] has no known check kind")
    return errors


def versions_block(config: dict, data: dict, prefix: str) -> str:
    status_cfg = config.get("site", {}).get("status", {})
    parts = []
    for entry in data["formalizations"].values():
        line = (f"{entry['name']} <a href=\"{entry['repo']}\">"
                f"<code>{entry['commit_auto']}</code></a>")
        if entry.get("mathlib_note"):
            line += (f"\n      ({entry['mathlib_note']}, "
                     f"<code>{entry.get('mathlib_commit_auto', '')}</code>)")
        parts.append(line)
    for extra in status_cfg.get("extras", []):
        parts.append(extra.format(**data))
    pdf_sha = data.get("pdf_sha256_auto", "")
    if pdf_sha and parts:
        parts[-1] += f" &middot; PDF sha256 <code>{pdf_sha[:12]}&hellip;</code>"
    tail_href = status_cfg.get("tail_href", "")
    tail_label = status_cfg.get("tail_label", tail_href.strip("/"))
    body = " &middot;\n      ".join(parts)
    if tail_href:
        body += f' &middot;\n      <a href="{prefix}{tail_href}">{tail_label}</a>'
    return f"""    Manuscript <a href="#" class="vknowl" data-vknowl="version-details"
       aria-expanded="false" title="Version identifiers">{data['manuscript_date']}</a>
    <span class="vknowl-panel" id="version-details" hidden>
      {body}
    </span>"""


BLOCKS = {
    "versions": versions_block,
}


def stamp_page(site: Path, page: Path, config: dict, data: dict) -> tuple[str, str]:
    """Return (old, new) content for a page, rewriting any marker blocks."""
    rel = page.relative_to(site)
    prefix = "../" * (len(rel.parts) - 1)
    text = page.read_text()
    new = text
    for name, render in BLOCKS.items():
        pat = re.compile(
            rf"(<!-- {name}:begin[^>]*-->\n).*?(\n\s*<!-- {name}:end -->)",
            re.DOTALL,
        )
        def repl(m, render=render, name=name):
            head = f"<!-- {name}:begin {STAMP_NOTE} -->\n"
            return head + render(config, data, prefix) + m.group(2)
        new = pat.sub(repl, new)
    return text, new


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("root", nargs="?", default=".", type=Path,
                    help="instance root (contains paper.toml)")
    ap.add_argument("--check", action="store_true",
                    help="verify only; exit 1 if stamped pages or status.json would change")
    args = ap.parse_args()

    root = args.root.resolve()
    config = load_config(root)
    site = site_dir(root, config)
    status_path = site / "status.json"

    data = json.loads(status_path.read_text())
    before = json.dumps(data, indent=2)
    data = refresh_auto(root, config, data)
    after = json.dumps(data, indent=2)

    errors = verify_hand_fields(root, config, data)
    for e in errors:
        print(f"gen-status ERROR: {e}", file=sys.stderr)

    changed = []
    if before != after:
        changed.append(status_path)
        if not args.check:
            status_path.write_text(after + "\n")

    for page in sorted(site.rglob("*.html")):
        old, new = stamp_page(site, page, config, data)
        if old != new:
            changed.append(page)
            if not args.check:
                page.write_text(new)

    if errors:
        return 1
    if args.check and changed:
        for p in changed:
            print(f"gen-status DRIFT: {p.relative_to(root)} is stale "
                  f"(run sitegen/gen_status.py)", file=sys.stderr)
        return 1
    if changed:
        print("gen-status: refreshed " + ", ".join(str(p.relative_to(root)) for p in changed))
    else:
        print("gen-status: everything current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
