#!/usr/bin/env python3
"""Generate the site favicon from the paper's own typeface.

The glyph outlines come from MathJax's New Computer Modern SVG font data
(a 1000-unit em, y-up, leading moveto implicit): paper.toml [site.favicon]
names a main glyph (font file + codepoint) and an optional subscript glyph,
set with TeX's script-size ratio and subscript drop, on a rounded tile.
The outlines are emboldened with a matching stroke: New CM's hairlines
vanish at 16 px, and a tab icon has to survive that.

Outputs, all under the site source dir ([site].dir):

    favicon.svg          the primary icon (every modern browser)
    favicon.ico          16/32/48 PNG-in-ICO, for bookmarks and old browsers
    apple-touch-icon.png 180x180, square (iOS applies its own corner mask)

Needs the npm packages under vendor/ (run `npm install` in vendor/ if the
font package is missing) and rsvg-convert for the raster outputs.
"""
from __future__ import annotations

import re
import shutil
import struct
import subprocess
import sys
from pathlib import Path

from _common import load_config, site_dir

NUMBER = re.compile(r"-?\d*\.?\d+")

DEFAULT_FONT_DIR = "vendor/node_modules/@mathjax/mathjax-newcm-font/svg"


def glyph(path: Path, code: int) -> str:
    """The SVG path data for one character, as MathJax stores it."""
    src = path.read_text()
    # entries look like  8474:[.704,.179,.777,{sk:.011,p:"653 87C674 ..."}]
    match = re.search(r'(?<![\d.])%d:\[[^\]]*?\{[^}]*?p:"([^"]*)"' % code, src)
    if not match:
        sys.exit(f"gen-favicon: no glyph {code} in {path}")
    data = match.group(1)
    return data if data[0].isalpha() else "M" + data  # leading moveto is implicit


def ink_box(data: str) -> tuple[float, float, float, float]:
    """Outer bound of a path: cubic segments stay inside their control points."""
    values = [float(t) for t in NUMBER.findall(data)]
    xs, ys = values[0::2], values[1::2]
    return min(xs), min(ys), max(xs), max(ys)


def render(font_dir: Path, cfg: dict, radius: float, pad: float) -> str:
    main_cfg = cfg["main"]
    tile = cfg.get("tile", "#1e5c3a")
    ink = cfg.get("ink", "#ffffff")
    embolden = cfg.get("embolden", 26)
    title = cfg.get("title", "")

    q = glyph(font_dir / main_cfg["file"], main_cfg["code"])
    qx0, qy0, qx1, qy1 = ink_box(q)
    x0, x1, y0, y1 = qx0, qx1, qy0, qy1

    sub_cfg = cfg.get("sub")
    sub_svg = ""
    if sub_cfg:
        two = glyph(font_dir.parent / "svg.js", ord(sub_cfg["char"]))
        tx0, ty0, tx1, ty1 = ink_box(two)
        scale = sub_cfg.get("scale", 0.78)
        drop = sub_cfg.get("drop", 125)
        sx = main_cfg["advance"] + sub_cfg.get("kern", 20)
        x0 = min(x0, sx + scale * tx0)
        x1 = max(x1, sx + scale * tx1)
        y0 = min(y0, -drop + scale * ty0)
        y1 = max(y1, -drop + scale * ty1)
        sub_svg = (f'<g transform="translate({sx} {-drop}) scale({scale})">'
                   f'<path d="{two}"/></g>\n')

    w, h = x1 - x0, y1 - y0

    # centre the ink box in the tile; the y axis flips (font coordinates are y-up)
    s = min((64 - 2 * pad) / w, (64 - 2 * pad) / h)
    dx, dy = (64 - s * w) / 2 - s * x0, (64 - s * h) / 2 + s * y1

    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
<!-- Generated by paperforge sitegen/gen_favicon.py. The outlines are New
     Computer Modern, as shipped in MathJax's SVG font data. -->
<title>{title}</title>
<rect width="64" height="64" rx="{radius}" fill="{tile}"/>
<g transform="translate({dx:.3f} {dy:.3f}) scale({s:.6f} {-s:.6f})"
   fill="{ink}" stroke="{ink}" stroke-width="{embolden}" stroke-linejoin="round">
<path d="{q}"/>
{sub_svg}</g>
</svg>
"""


def rasterize(svg: Path, png: Path, size: int) -> None:
    subprocess.run(
        ["rsvg-convert", "-w", str(size), "-h", str(size), str(svg), "-o", str(png)],
        check=True,
    )


def write_ico(pngs: list[Path], out: Path) -> None:
    """Pack PNG images into an .ico container (PNG-in-ICO, Vista and later)."""
    images = [p.read_bytes() for p in pngs]
    sizes = [int(re.search(r"-(\d+)\.png$", p.name).group(1)) for p in pngs]
    offset = 6 + 16 * len(images)
    header = struct.pack("<HHH", 0, 1, len(images))
    directory, body = b"", b""
    for size, image in zip(sizes, images):
        directory += struct.pack(
            "<BBBBHHII", size % 256, size % 256, 0, 0, 1, 32, len(image), offset
        )
        offset += len(image)
        body += image
    out.write_bytes(header + directory + body)


def main() -> None:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
    config = load_config(root)
    cfg = config.get("site", {}).get("favicon")
    if not cfg or "main" not in cfg:
        sys.exit("gen-favicon: no [site.favicon].main configured")
    font_dir = root / cfg.get("font_dir", DEFAULT_FONT_DIR)
    if not font_dir.exists():
        sys.exit(f"gen-favicon: {font_dir} missing — run `npm install` in vendor/")
    site = site_dir(root, config)
    radius = cfg.get("radius", 13)

    favicon = site / "favicon.svg"
    favicon.write_text(render(font_dir, cfg, radius=radius, pad=3))
    print(f"wrote {favicon.relative_to(root)}")

    if not shutil.which("rsvg-convert"):
        print("gen-favicon: rsvg-convert missing — skipped .ico and apple-touch-icon")
        return

    work = site / ".favicon-work"
    work.mkdir(exist_ok=True)
    try:
        pngs = []
        for size in (16, 32, 48):
            png = work / f"favicon-{size}.png"
            rasterize(favicon, png, size)
            pngs.append(png)
        write_ico(pngs, site / "favicon.ico")
        print(f"wrote {(site / 'favicon.ico').relative_to(root)} (16/32/48)")

        # iOS masks the corners itself and shows the icon large, so the touch
        # icon is square and sits on a wider margin.
        square = work / "touch.svg"
        square.write_text(render(font_dir, cfg, radius=0, pad=7))
        rasterize(square, site / "apple-touch-icon.png", 180)
        print(f"wrote {(site / 'apple-touch-icon.png').relative_to(root)} (180x180)")
    finally:
        shutil.rmtree(work, ignore_errors=True)


if __name__ == "__main__":
    main()
